### ISSUE TITLE
Java NetworkTables Server incorrectly encodes Supplementary Multilingual Plane with Surrogate Pairs (artf3973)

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/ntcore#69]
The NWT spec says that all strings are UTF8. Pasting the string "cat🐱mouse" ("cat\u{1F431}mouse") in outline viewer as a server should encode it in UTF-8 as the binary string "cat\xF0\x9F\x90\xB1mouse". However the actual string sent across the network is "cat\xED\xA0\xBD\xED\xB0\xB1mouse" which is the UTF-8 encoding of "cat\xD8\x3D\xDC\x31mouse", where "\uD83D\uDC31" is the UTF-16 surrogate pair encoding of \u{1F431} (🐱)

Thus, it appears that surrogate pairs for characters that are not in Unicode Plane 0 are not being re-encoded in utf-8 properly. 

Sending a correct UTF-8 encoding ("cat\xF0\x9F\x90\xB1mouse") via a custom C++ NWT client causes the java server to crash and Outline viewer to stop responding to updates or sending out updates and this error is printed:

`edu.wpi.first.wpilibj.networktables2.server.ServerConnectionAdapter@6a59828c entered connection state: SERVER_ERROR: class java.io.UTFDataFormatException: malformed input around byte 3`

**Comment by ThadHouse** [comment]
So looking around, a way around this issue is to pass the raw arrays up to Java, and then do the conversion. Same thing for going the other way. However, that is definitely going to cause some performance issues, as we will basically be doing a conversions from native array to java array, then java array to java string.

http://bitbrothers.org/blog/2013/08/jni-strings-modified-utf8-oh-my/
